### ISSUE TITLE
Support for long press (for tooltips)?

### ISSUE THREAD

**Issue by benzabill** [ceryle/RadioRealButton#10]
Fantastic library, thank you so much.

Looking to apply a long press so that I can display a small tooltip with more information about the icon/radio button - but applying a OnLongClick listener doesn't fire.

Is this possible? My current solution is going to be to show a snackbar

**Comment by ceryle** [comment]
Thank you :)
I have updated the library and new version is "v1.4.9" now. You can use onLongClickedButton listener.

**Comment by benzabill** [comment]
Thank you! The first time i tried it, i used the standard longclick listener and it didn't work - but then I found that you had put in your own long click listener. I like that you did this, as you give a handle onto the "position", but this may be confusing to people going forward -  perhaps a note in the readme?

Another thing, you changed the name of  "OnClickedButtonPosition" to "OnClickedButtonListener" without changing the example in the readme! 

Thanks again.

**Comment by ceryle** [comment]
Sorry I forgot adding info in ReadMe file, I didn't have time yesterday. I will edit it right away.
