### ISSUE TITLE
RadioButton options problem

### ISSUE THREAD

**Issue by fifisamy** [ceryle/RadioRealButton#11]
icannot change button text color programmatically ..not working 

icannot change RadioRealGroup height Or  RadioRealButton height ..not working

**Comment by ceryle** [comment]
Ok, I will take a look at those issues.

**Comment by fifisamy** [comment]
thanks :)

**Comment by ceryle** [comment]
Hi, I resolved two issues, but changing button's height will still be not working. I am planning to improve the library with major changes in the near future, and solve this issue, too.
