### ISSUE TITLE
Background color not working

### ISSUE THREAD

**Issue by csbenz** [ceryle/RadioRealButton#13]
I tried taking the sample app and changing the RadioRealButtonGroup background color with `  app:rrbg_backgroundColor="@color/black"`, but it doesn't change.
I'm on a Nexus 5X Android 7.1.

**Comment by ceryle** [comment]
I will take a look at this issue soon, csbenz.

**Comment by csbenz** [comment]
Thanks, have you found anything yet? :)

**Comment by ceryle** [comment]
I was working on a new update and I am planning to release it next week. I believe it will be available monday or tuesday. I hope it is not too late for you :)

**Comment by csbenz** [comment]
That's perfect, I'm going to release my app during the course of next week :)

**Comment by ceryle** [comment]
Good luck 😊

**Comment by ceryle** [comment]
Hi csbenz, it looks like it will take longer than I thought to complete the new update. However, I released a new version with a quick fix for background issue. (new version is v1.5.1)

**Comment by csbenz** [comment]
Just tested, it works fine! Thank you :)

I'll leave it up to you to close this issue, I don't know if you want to keep it open till you make a stronger fix.

**Comment by ceryle** [comment]
Thanks, I can close it because this fix should work fine and you're welcome :)
