### ISSUE TITLE
Default one radio button checked?

### ISSUE THREAD

**Issue by munimisu** [ceryle/RadioRealButton#15]
I am trying to set one radio button checked as default. I used android:checked="true" on radio button, and             android:checkedButton="@id/button1" in radiogroup; but none of them work. 

Can you please add or describe how to default check a radio button?

Thanks!

**Comment by ceryle** [comment]
Hi munimisu,
You can check a button using (app:rrbg_position="0") in XML and setPosition(0) in Java code. This attribute is one of group's attributes. Also, I am planning to add checked attribute that you mentioned in new versions.

**Comment by munimisu** [comment]
Thanks ceryle! I will try that. Looking forward to new version.
