### ISSUE TITLE
RadioRealButton gravity

### ISSUE THREAD

**Issue by ipserlionel** [ceryle/RadioRealButton#16]
Hello,

First, great job!

Is it possible to add an option for "gravity" in each RadioRealButton? If the text is too long, it's on the left of the RadioRealButton zone.
![radiorealbutton gravity](https://cloud.githubusercontent.com/assets/1357185/23340840/6f1ae410-fc3d-11e6-818c-781139363a3d.jpg)

Thanks,

Lionel

**Comment by ceryle** [comment]
Hi,
First thank you :) Yes, I can add that attribute. I will release a new version in this week and that attribute will be included.

**Comment by ceryle** [comment]
Hi, in new version(2.0.0) you can use textGravity attribute to make text centered.
