### ISSUE TITLE
Attribute X has already been defined

### ISSUE THREAD

**Issue by lionelatrecisio** [ceryle/RadioRealButton#17]
Hello,

Thank you very much for adding gravity to the views ;)

But with the 2.0.0 version, you deleted rrbg_ suffix to your attributes, so I've got "Attribute "rippleColor" has already been defined" error at build time for example.

Is it possible to rollback to previous suffix, or tell me how to deal with this problem?

Thanks,

Lionel

**Comment by ceryle** [comment]
Did you make a clean build, because I tested there wasn't any error. Do you think problem occurs because other libraries' attributes have the same attribute name with this library? I didn't know if it happens because of that.

**Comment by lionelatrecisio** [comment]
Ok, 

So apparently it cames from :

FloatingActionButton

which is in :

compile 'com.android.support:design:25.2.0'

**Comment by lionelatrecisio** [comment]
I know that it could be unpleasant, but is it possible to bring back the suffix?

Maybe I'll not be the only one with this kind of problem

**Comment by ceryle** [comment]
I tried it, and it seems working. I really don't know why it behaves like that. However, I will add prefixes back to solve your issue and also someone may face this issue too, as you said :)

**Comment by ceryle** [comment]
Hi lionel, I added prefixes. You can use the new version which is v2.0.1
