### ISSUE TITLE
setPosition is not updating selector position

### ISSUE THREAD

**Issue by MeinLieberScholli** [ceryle/RadioRealButton#18]
Hi,
i updated to your newest version 2.0.2 and now have the weird problem that the selector position won't be updated after i set the position programmatically. The current position of the button group is correctly set and i can't click the setted button but the selector is still on the old position. It's weird because i tried your sample app which works fine. I did some debugging, but couldn't really find anything. I also put the setPosition command in a rxandroid observable to make sure that it gets executed on the main thread.
Hope you can help me.

Here is my XML code:
`<co.ceryle.radiorealbutton.library.RadioRealButtonGroup
                android:id="@+id/btnSelfAssessment"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:rrbg_dividerColor="@color/seperator"
                app:rrbg_dividerSize="1dp"
                app:rrbg_selectorColor="@color/colorAccent"
                app:rrbg_selectorSize="6dp"
                app:rrbg_radius="10dp"
                app:rrbg_borderSize="2dp"
                app:rrbg_borderColor="@color/seperator"
                app:rrbg_checkedPosition="0">
                <co.ceryle.radiorealbutton.library.RadioRealButton
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:rrb_ripple="true"
                    app:rrb_rippleColor="@color/colorAccent"
                    app:rrb_text="@string/btn_beginner"
                    app:rrb_textSize="16dp"
                    app:rrb_textColor="@android:color/black"/>
                <co.ceryle.radiorealbutton.library.RadioRealButton
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:rrb_ripple="true"
                    app:rrb_rippleColor="@color/colorAccent"
                    app:rrb_text="@string/btn_advanced"
                    app:rrb_textSize="16dp"
                    app:rrb_textColor="@android:color/black"/>
                <co.ceryle.radiorealbutton.library.RadioRealButton
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:rrb_ripple="true"
                    app:rrb_rippleColor="@color/colorAccent"
                    app:rrb_text="@string/btn_expert"
                    app:rrb_textSize="16dp"
                    app:rrb_textColor="@android:color/black"/>
            </co.ceryle.radiorealbutton.library.RadioRealButtonGroup>`

**Comment by ceryle** [comment]
Hi MeinLieberScholli,
Yes, I see the problem. I will take care of that and notify you when it is fixed.

**Comment by ceryle** [comment]
Hi,
I updated the library, I believe it is fixed now.

**Comment by MeinLieberScholli** [comment]
Yes, it's fixed. Thank you for the quick response!

**Comment by ceryle** [comment]
You're welcome :)
