### ISSUE TITLE
setPosition() on RadioRealGroup bug on v2.0.2

### ISSUE THREAD

**Issue by viini42** [ceryle/RadioRealButton#20]
On your page you must update the compile line to 
`compile 'com.github.ceryle:RadioRealButton:v2.0.4'`

When I'm using the v2.0.2 the setPosition() is working but the selector is not working

**Comment by ceryle** [comment]
Hi,
I've already updated dependency section. Yes, there was a bug in that version, and I've fixed that. Do you still have it in version 2.0.4?

**Comment by viini42** [comment]
Yes, I do. When I initialize my fragment, the setPosition() work, but when I call this method on a Listening, this not work

**Comment by ceryle** [comment]
I tested setPostion method, it seems working. Can you provide more information or share your code? Also, there is an example in sample project, I have used it to test setPosition method, it works for all button groups.
