### ISSUE TITLE
[Question] Color selector per item

### ISSUE THREAD

**Issue by Alex293** [ceryle/RadioRealButton#24]
What would be the best way to get one selector color per item ?

As the selector move with animation for one item to another I trying to find a way to change it in the middle of the animation or something like this

**Comment by Alex293** [comment]
Seems that on RadioRealButtonGroup methods like setSelectorColor don't do anything as attributes seems to be used only at init

**Comment by ceryle** [comment]
Yes, setSelectorColor method is not working after creation of the view. This one and some other methods do nothing at runtime, and I will fix those in the next release. I also want to add color transition animation to selector too. Probably, it will be available next week.

**Comment by Alex293** [comment]
Awesome ! ping me when you have a testable version I'll play with and give you feed back.

**Comment by ceryle** [comment]
Hi again,
You can set selector color for each checked button now. However, if you set rrbg_selectorAnimationType to translate_x, it won't work for now. For other animation types, it works good.
