### ISSUE TITLE
More complete listener

### ISSUE THREAD

**Issue by Alex293** [ceryle/RadioRealButton#25]
Continuing improvement related to #24 it could be useful to have the previous position on change listeners. Like onPositionChanged(RadioRealButton button, int from, int to)

We then have the ability the change to color of the selected item and then restore it to its previous color when some other item is selected.

**Comment by ceryle** [comment]
Hi again,
I added your request to onPositionChangedListener. It makes much sense now, since this listener deals only position changes.
