### ISSUE TITLE
Deselect selected item programmatically

### ISSUE THREAD

**Issue by gencaysahinn** [ceryle/RadioRealButton#26]
Hello, 
Firstly thanks for this great library. I would like to deselect selected item programmatically. I tried to use deselect() method but it didn't work. How can I do that?

**Comment by ceryle** [comment]
Hi Gencay,
You're welcome :). It seems that this method only works for translate_x animationType. I will fix that in the next release.

**Comment by ceryle** [comment]
Hi,
I believe it is fixed now. Whether its deselection mode is enabled or not, it still has to work.

**Comment by gencaysahinn** [comment]
Yes It works now. Thanks again :)
