### ISSUE TITLE
Any Licence Problem

### ISSUE THREAD

**Issue by gokhanylmz** [ceryle/RadioRealButton#45]
Hey there,
I'm new on Android and GitHub. I 'm still working on my Android project, I want to publish on Play Store.
I want to ask:
- if I use this button style on my project, Is there any license problem?
-Same question about another styles on GitHub.

Please answer to me, that's important to me..

**Comment by AyoPrez** [comment]
Generally all the open source projects has an Apache 2, MIT or BSD license (probably there are more licenses, but those are the most common).  If you carefully read the license (something that you should do), you will see that they more or less say the same. 

At the end, you can use the projects but somewhere in the app you should name the author and what kind of license the project has. You can do this in the terms & conditions or in a licenses screen. Up to you.   

What happen if you don't do it? Well, you are braking the license and the creator of the project can sue you. Anyway, I think that naming them is the minimum to do after what they offer use liberating the code and making us save tons of hours of development. :)

**Comment by gokhanylmz** [comment]
Thanks for answer, you explained clearly. 

I respect them and I will add their names to my project but can you share any detail or standards this work? I didn't need any license on my project so I don't have license screen or something like that. 

Short story: I don't know what I will write to license screen, can you advice any example or tutorial or source about that?

**Comment by AyoPrez** [comment]
Normally I write the name of the project or library, then the name of the author and the kind of license the project has. Apache 2 license text should be in the project somewhere. This text is in the license of the project. Here a link: 
https://github.com/ceryle/RadioRealButton/blob/master/LICENSE.txt

Happy to help 😃

**Comment by gokhanylmz** [comment]
Thank you so much, really you helped to me 😄👍
