### ISSUE TITLE
No method/xml attribute to set text size

### ISSUE THREAD

**Issue by benzabill** [ceryle/RadioRealButton#5]
On screens of different sizes, the text doesn't look big enough.

Is this missing or am I missing something

**Comment by ceryle** [comment]
You are not missing anything, that was a missing attribute. I added these following attributes; size, style and typeface for text. New version is v1.4.5 now.

**Comment by benzabill** [comment]
Thanks, exactly what I needed! Great functionality/library (don't forget to update the readme :) )
