### ISSUE TITLE
No setChecked(boolean)

### ISSUE THREAD

**Issue by bkolarov-appolica** [ceryle/RadioRealButton#6]
Hi,
I didn't see a way to deselect all buttons in RadioRealButtonGroup. Also the RadioRealButton view doesn't have setChecked(boolean) method, so I can't go through all of the buttons in the group and deselect them. Do you intend to change this any time soon? 

Thank you for your time :)

**Comment by ceryle** [comment]
Hello,
Ok, I will take a look that issue soon.

**Comment by ceryle** [comment]
Hi again,
I have added a new method which is deselect(). With this method you can deselect if there has been made any selection. Moreover, if you don't give any position to group in xml, there will be no visible selection too. Current version is v1.4.7 now.
