### ISSUE TITLE
Add possibilitxy for border

### ISSUE THREAD

**Issue by csbenz** [ceryle/RadioRealButton#7]
Hi ceryle, great lib! I love it.
It would be useful to be able to add a simple border (with radius, like now) instead of a shadow. I'm using RadioRealButton inside another card and it doesn't look great with the shadow.

Thanks :)

**Comment by ceryle** [comment]
Thanks csbenz. This week, I will update the library and when it is done I will inform you. Happy coding :)

**Comment by ceryle** [comment]
You can set borders now and also you can take a look to the sample project which has an example for setting border.
