### ISSUE TITLE
Bug - Text size can shrink to infinity

### ISSUE THREAD

**Issue by csbenz** [ceryle/RadioRealButton#8]
When you select a radio button, the text size increases, and it then decreases when you select another button.
It look like there isn't a default size for the non-selected text, and that it increases/decreases by percent. Therefore it is possible to rapidly select a radio button then another many times, and the text will shrink or get bigger and stay like that.
I can provide a picture if needed.

**Comment by ceryle** [comment]
Hi csbenz,
This issue is fixed with the new update which is v1.4.7.

**Comment by csbenz** [comment]
Work for me, thanks a lot ceryle!
