### ISSUE TITLE
setEnabled not effective

### ISSUE THREAD

**Issue by lionelatrecisio** [ceryle/RadioRealButton#9]
Hello,

First of all, your library is great!

Is it possible to implement the setEnabled(boolean), in order to enable or disable the group?

Thanks,

Lionel

**Comment by ceryle** [comment]
Hi,
Firstly, thank you. Yes, I will add this feature in a week.

**Comment by ceryle** [comment]
Hi again,
I have added two features. One is rrbg_enabled and the second one android:clickable. If you use rrbg_enabled attribute you will see that group will be grayed out.
